export const dummyUsers = [
  {
    firstName: "Aditya",
    lastName: "Bharti",
    email: "aditya@techdocklabs.com",
    phoneNumber: "1234567897",
    password: "123456789",
    confirmPassword: "123456789",
    status: "enabled",
    zipCode: "224001",
    country: "India",
    state: "Uttar Pradesh",
    city: "Lucknow",
    address: "123 Main St, Faizabad, Lucknow",
    branchName: "Faizabad",
    profileImage: new File([""], "51Y7HQIINrL._SL1000_.jpg", {
      type: "image/jpeg",
    }),
    role: "Admin",
  },
  {
    firstName: "Rahul",
    lastName: "Kumar",
    email: "rahul@example.com",
    phoneNumber: "9876543210",
    password: "password123",
    confirmPassword: "password123",
    status: "enabled",
    zipCode: "224002",
    country: "India",
    state: "Uttar Pradesh",
    city: "Lucknow",
    address: "456 Elm St, Lucknow",
    branchName: "Faizabad",
    profileImage: new File([""], "profile1.jpg", { type: "image/jpeg" }),
    role: "Staff",
  },
  {
    firstName: "Sita",
    lastName: "Singh",
    email: "sita@example.com",
    phoneNumber: "8765432109",
    password: "mypassword",
    confirmPassword: "mypassword",
    status: "enabled",
    zipCode: "224003",
    country: "India",
    state: "Uttar Pradesh",
    city: "Kanpur",
    address: "789 Pine St, Kanpur",
    branchName: "Kanpur Branch",
    profileImage: new File([""], "profile2.jpg", { type: "image/jpeg" }),
    role: "User",
  },
  {
    firstName: "Mohammed",
    lastName: "Ali",
    email: "mohammed@example.com",
    phoneNumber: "1234567898",
    password: "pass1234",
    confirmPassword: "pass1234",
    status: "disabled",
    zipCode: "224004",
    country: "India",
    state: "Uttar Pradesh",
    city: "Agra",
    address: "321 Oak St, Agra",
    branchName: "Agra Branch",
    profileImage: new File([""], "profile3.jpg", { type: "image/jpeg" }),
    role: "Merchant",
  },
  {
    firstName: "Anita",
    lastName: "Sharma",
    email: "anita@example.com",
    phoneNumber: "2345678901",
    password: "anita123",
    confirmPassword: "anita123",
    status: "enabled",
    zipCode: "224005",
    country: "India",
    state: "Uttar Pradesh",
    city: "Varanasi",
    address: "654 Birch St, Varanasi",
    branchName: "Varanasi Branch",
    profileImage: new File([""], "profile4.jpg", { type: "image/jpeg" }),
    role: "Staff",
  },
  {
    firstName: "Vikram",
    lastName: "Desai",
    email: "vikram@example.com",
    phoneNumber: "3456789012",
    password: "vikram123",
    confirmPassword: "vikram123",
    status: "enabled",
    zipCode: "224006",
    country: "India",
    state: "Uttar Pradesh",
    city: "Bareilly",
    address: "987 Cedar St, Bareilly",
    branchName: "Bareilly Branch",
    profileImage: new File([""], "profile5.jpg", { type: "image/jpeg" }),
    role: "Admin",
  },
  {
    firstName: "Priya",
    lastName: "Mishra",
    email: "priya@example.com",
    phoneNumber: "4567890123",
    password: "priya123",
    confirmPassword: "priya123",
    status: "disabled",
    zipCode: "224007",
    country: "India",
    state: "Uttar Pradesh",
    city: "Ghaziabad",
    address: "111 Maple St, Ghaziabad",
    branchName: "Ghaziabad Branch",
    profileImage: new File([""], "profile6.jpg", { type: "image/jpeg" }),
    role: "User",
  },
  {
    firstName: "Deepak",
    lastName: "Verma",
    email: "deepak@example.com",
    phoneNumber: "5678901234",
    password: "deepak123",
    confirmPassword: "deepak123",
    status: "enabled",
    zipCode: "224008",
    country: "India",
    state: "Uttar Pradesh",
    city: "Noida",
    address: "222 Willow St, Noida",
    branchName: "Noida Branch",
    profileImage: new File([""], "profile7.jpg", { type: "image/jpeg" }),
    role: "Merchant",
  },
  {
    firstName: "Neha",
    lastName: "Bansal",
    email: "neha@example.com",
    phoneNumber: "6789012345",
    password: "neha123",
    confirmPassword: "neha123",
    status: "enabled",
    zipCode: "224009",
    country: "India",
    state: "Uttar Pradesh",
    city: "Meerut",
    address: "333 Spruce St, Meerut",
    branchName: "Meerut Branch",
    profileImage: new File([""], "profile8.jpg", { type: "image/jpeg" }),
    role: "Staff",
  },
  {
    firstName: "Rahul",
    lastName: "Kumar",
    email: "rahulk@example.com",
    phoneNumber: "7890123456",
    password: "rahul123",
    confirmPassword: "rahul123",
    status: "disabled",
    zipCode: "224010",
    country: "India",
    state: "Uttar Pradesh",
    city: "Allahabad",
    address: "444 Fir St, Allahabad",
    branchName: "Allahabad Branch",
    profileImage: new File([""], "profile9.jpg", { type: "image/jpeg" }),
    role: "User",
  },
  {
    firstName: "Pooja",
    lastName: "Garg",
    email: "pooja@example.com",
    phoneNumber: "8901234567",
    password: "pooja123",
    confirmPassword: "pooja123",
    status: "enabled",
    zipCode: "224011",
    country: "India",
    state: "Uttar Pradesh",
    city: "Saharanpur",
    address: "555 Palm St, Saharanpur",
    branchName: "Saharanpur Branch",
    profileImage: new File([""], "profile10.jpg", { type: "image/jpeg" }),
    role: "Merchant",
  },
];
